spring.application.name=order-service

# Exposer l'endpoint /actuator/health sans restriction
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
server.port=8081